### ISSUE TITLE
It is allowing to access the API data after logout

### ISSUE THREAD

**Issue by shahidmau** [jpotts18/mean-stack-relational#43]
I can open this url http://localhost:3000/articles after logout, is there any way to pass access token to access secure contents and that token must be invalidated after logout?

**Comment by chaudhryjunaid** [comment]
@shahidmau currently passport is being used in association with express session to track user login status. The url in question can be easily restricted to a logged in user by adding `users.requiresLogin` middleware to the request path as in other requests. This is intended to be a base project and since a list of all articles could be public on a news website, this middleware is not added by default. 

If you have additional concerns, please state. I will close the issue after a while if you have no further comment.
